# Docker Compose configuration for QoL Backend API

# Common service configuration used by all services
x-service-common: &service-common
  env_file:
    # Base application configuration (optional)
    - path: config/app.env
      required: false

services:
  #################################################################
  ## PRODUCTION
  #################################################################
  prod:
    <<: *service-common
    build:
      context: .
      target: prod

  #################################################################
  ## TESTING
  #################################################################
  # Testing app (standalone)
  testing:
    <<: *service-common
    build:
      context: .
      target: testing

  # Testing app with database
  testing-db:
    <<: *service-common
    build:
      context: .
      target: testing
    env_file:
      # Database environment configuration (required)
      - path: config/db.env
        required: true
    depends_on:
      - db

  #################################################################
  ## DEVELOPMENT
  #################################################################
  # Development app (standalone)
  dev:
    <<: *service-common
    build:
      context: .
      target: dev
    # Fix file permission issues with bind mounts
    user: "1000:1000"
    working_dir: /qol_backend_api
    init: true
    env_file:
      # Developer-specific environment overrides (optional)
      - path: config/dev.env
        required: false
    volumes:
      # Mount the current directory to /qol_backend_api for live development
      - .:/qol_backend_api:cached

  # Development app with database
  dev-db:
    <<: *service-common
    build:
      context: .
      target: dev
    # Fix file permission issues with bind mounts
    user: "1000:1000"
    working_dir: /qol_backend_api
    init: true
    env_file:
      # Database environment configuration (required)
      - path: config/db.env
        required: true
      # Developer-specific environment overrides (optional)
      - path: config/dev.env
        required: false
    volumes:
      # Mount the current directory to /qol_backend_api for live development
      - .:/qol_backend_api:cached
    depends_on:
      - db
      
  #################################################################
  ## DATABASE
  #################################################################
  # Shared database for both development and testing
  db:
    image: mysql:8.4
    env_file:
      # Database environment configuration (required)
      - path: config/db.env
        required: true
    ports:
      - "3306:3306"

#################################################################
## USAGE GUIDE
#################################################################
#
# Run commands:
#   Production:       docker compose up --build prod
#   Testing:          docker compose run --build --rm testing
#   Testing with DB:  docker compose run --build --rm testing-db
#   Development:      docker compose up --build dev
#   Dev with DB:      docker compose up --build dev-db
#
# Configuration Files:
#   config/app.env  - Application settings (optional, used by all services)
#   config/db.env   - Database settings (REQUIRED for database services)
#   config/dev.env  - Developer overrides (optional, only for dev services)
#
# Environment File Precedence (later files override earlier ones):
#   1. config/app.env (loaded first via x-service-common)
#   2. config/db.env (loaded in database services)
#   3. config/dev.env (loaded last in development services for highest priority)
#
# Developer Tools:
#   config/apt-build-packages.txt     - Build dependencies for Python packages
#   config/apt-runtime-packages.txt   - Interactive development tools
#   config/python-dev-packages.txt    - Custom Python packages for dev container